// src/pages/user/UserOrders/styles.js
export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#111827',
    margin: 0,
  },
  subtitle: {
    fontSize: '14px',
    color: '#6b7280',
    marginTop: '4px',
  },
  ordersList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  orderCard: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    border: '1px solid #f3f4f6',
    overflow: 'hidden',
    transition: 'box-shadow 0.2s',
  },
  orderHeader: {
    padding: '16px 24px',
    backgroundColor: '#f9fafb',
    borderBottom: '1px solid #f3f4f6',
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
  },
  headerInfoGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  headerLabel: {
    fontSize: '14px',
    color: '#6b7280',
    marginBottom: '2px',
  },
  headerValue: {
    fontWeight: '600',
    color: '#111827',
    fontSize: '14px',
  },
  statusBadge: {
    padding: '4px 12px',
    borderRadius: '9999px',
    fontSize: '12px',
    fontWeight: '500',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  orderBody: {
    padding: '16px 24px',
  },
  productsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '16px',
  },
  productImages: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  imageList: {
    display: 'flex',
    marginLeft: '-8px', // For negative margin effect
  },
  imageWrapper: {
    width: '48px',
    height: '48px',
    borderRadius: '8px',
    border: '2px solid #fff',
    backgroundColor: '#f3f4f6',
    overflow: 'hidden',
    flexShrink: 0,
    marginLeft: '-8px', // Overlap
    position: 'relative',
    textDecoration: 'none',
    display: 'block',
    transition: 'transform 0.2s',
  },
  productImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  moreCount: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e5e7eb',
    fontSize: '12px',
    fontWeight: '500',
    color: '#4b5563',
  },
  itemCount: {
    fontSize: '14px',
    color: '#6b7280',
    marginTop: '8px',
  },
  addressInfo: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    fontSize: '14px',
    color: '#4b5563',
  },
  totalPrice: {
    textAlign: 'right',
  },
  priceLabel: {
    fontSize: '14px',
    color: '#6b7280',
  },
  priceValue: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#111827',
  },
  orderFooter: {
    padding: '12px 24px',
    backgroundColor: '#f9fafb',
    borderTop: '1px solid #f3f4f6',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailLink: {
    color: '#2563eb',
    fontWeight: '500',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: 'auto',
    textDecoration: 'none',
    cursor: 'pointer',
  },
  pagination: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    paddingTop: '16px',
  },
  pageButton: {
    padding: '8px 16px',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
    fontSize: '14px',
    fontWeight: '500',
    color: '#4b5563',
    backgroundColor: '#fff',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  pageInfo: {
    padding: '8px 16px',
    fontSize: '14px',
    color: '#4b5563',
  },
  emptyState: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    padding: '48px',
    textAlign: 'center',
  },
  emptyIcon: {
    width: '64px',
    height: '64px',
    color: '#d1d5db',
    margin: '0 auto 16px',
  },
  emptyTitle: {
    fontSize: '18px',
    fontWeight: '500',
    color: '#111827',
    marginBottom: '8px',
  },
  emptyText: {
    color: '#6b7280',
    marginBottom: '24px',
  },
  shopButton: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '12px 24px',
    backgroundColor: '#2563eb',
    color: '#fff',
    borderRadius: '12px',
    fontWeight: '500',
    textDecoration: 'none',
    transition: 'background-color 0.2s',
  },
  loadingContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px',
  },
  errorContainer: {
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: '12px',
    padding: '24px',
    textAlign: 'center',
  },
};
