// src/components/common/CategoryMenu/styles.js

export const categoryMenuStyles = {
  container: {
    position: 'relative',
  },
  menuList: {
    display: 'flex',
    alignItems: 'center',
    gap: '32px',
    listStyle: 'none',
    margin: 0,
    padding: 0,
    height: '100%',
  },
  menuItem: {
    position: 'relative',
  },
  menuLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 16px',
    color: '#1e293b',
    textDecoration: 'none',
    fontSize: '15px',
    fontWeight: '500',
    borderRadius: '8px',
    transition: 'all 0.2s ease',
  },
  activeLink: {
    backgroundColor: '#f0fdf4',
    color: '#059669',
  },
  megaMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    backgroundColor: 'white',
    boxShadow: '0 10px 40px rgba(0, 0, 0, 0.1)',
    borderRadius: '12px',
    padding: '24px',
    minWidth: '600px',
    maxWidth: '900px',
    zIndex: 1000,
    opacity: 0,
    visibility: 'hidden',
    transform: 'translateY(-10px)',
    transition: 'all 0.3s ease',
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
    gap: '24px',
    marginTop: '8px',
  },
  megaMenuActive: {
    opacity: 1,
    visibility: 'visible',
    transform: 'translateY(0)',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  columnTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#059669',
    marginBottom: '8px',
    padding: '8px 12px',
    backgroundColor: '#f0fdf4',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  subList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  subItem: {
    padding: '8px 12px',
    fontSize: '13px',
    color: '#64748b',
    textDecoration: 'none',
    borderRadius: '6px',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
  },
  subItemHover: {
    backgroundColor: '#f8fafc',
    color: '#059669',
  },
};
