// src/pages/user/UserAddresses/styles.js

export const getStyles = (isMobile) => ({
  container: {
    fontFamily: '"Inter", sans-serif',
    color: '#1e293b',
  },
  header: {
    marginBottom: isMobile ? '20px' : '32px',
    display: 'flex',
    flexDirection: isMobile ? 'column' : 'row',
    justifyContent: 'space-between',
    alignItems: isMobile ? 'flex-start' : 'center',
    gap: isMobile ? '12px' : '0',
  },
  title: {
    fontSize: isMobile ? '18px' : '20px',
    fontWeight: '700',
    color: '#1e293b',
  },
  addButton: {
    backgroundColor: '#059669',
    color: 'white',
    border: 'none',
    padding: isMobile ? '10px 16px' : '10px 20px',
    borderRadius: '10px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: isMobile ? '13px' : '14px',
    transition: 'background 0.2s',
    width: isMobile ? '100%' : 'auto',
    justifyContent: 'center',
  },
  formCard: {
    backgroundColor: 'white',
    padding: isMobile ? '20px' : '32px',
    borderRadius: '24px',
    border: '1px solid #f1f5f9',
    marginBottom: isMobile ? '20px' : '32px',
    boxShadow: '0 4px 20px -2px rgba(0, 0, 0, 0.05)',
  },
  formHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '32px',
    paddingBottom: '16px',
    borderBottom: '1px solid #f1f5f9',
  },
  formTitle: {
    fontSize: isMobile ? '18px' : '20px',
    fontWeight: '700',
    margin: 0,
    color: '#0f172a',
    letterSpacing: '-0.5px',
  },
  closeButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#94a3b8',
    padding: '8px',
    borderRadius: '50%',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: '600',
    color: '#334155',
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    padding: isMobile ? '12px 16px 12px 40px' : '14px 16px 14px 44px',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    outline: 'none',
    fontSize: '14px',
    transition: 'all 0.2s ease',
    backgroundColor: '#f8fafc',
    color: '#1e293b',
    boxSizing: 'border-box',
    fontWeight: '500',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr',
    gap: isMobile ? '12px' : '16px',
    marginBottom: isMobile ? '12px' : '16px',
  },
  addressCard: {
    backgroundColor: 'white',
    padding: isMobile ? '16px' : '20px',
    borderRadius: isMobile ? '12px' : '16px',
    border: '1px solid #e2e8f0',
    marginBottom: 0,
    position: 'relative',
    transition: 'all 0.2s',
  },
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '8px',
    marginTop: '24px',
  },
  pageBtn: {
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
    border: '1px solid #e2e8f0',
    backgroundColor: 'white',
    color: '#64748b',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s',
  },
  activePageBtn: {
    backgroundColor: '#059669',
    color: 'white',
    borderColor: '#059669',
  },
  addressCardDefault: {
    border: '2px solid #059669',
    backgroundColor: '#f0fdf4',
  },
  defaultBadge: {
    position: 'absolute',
    top: '-10px',
    right: '16px',
    backgroundColor: '#059669',
    color: 'white',
    padding: isMobile ? '3px 10px' : '4px 12px',
    borderRadius: '12px',
    fontSize: isMobile ? '10px' : '11px',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  labelBadge: {
    backgroundColor: '#ecfdf5',
    color: '#059669',
    padding: isMobile ? '3px 8px' : '4px 10px',
    borderRadius: '6px',
    fontSize: isMobile ? '11px' : '12px',
    fontWeight: '600',
  },
  actionButton: {
    padding: isMobile ? '6px' : '8px',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingContainer: {
    padding: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200
  },
  spinner: {
    fontSize: 24,
    color: '#059669',
    animation: 'spin 1s linear infinite',
  },
  emptyState: {
    textAlign: 'center',
    padding: '40px 20px',
    backgroundColor: '#f8fafc',
    borderRadius: '16px',
    border: '2px dashed #e2e8f0',
    color: '#64748b',
  },
  inputIcon: {
    position: 'absolute',
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94a3b8',
    fontSize: '14px',
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  submitButton: {
    backgroundColor: '#059669',
    color: 'white',
    border: 'none',
    padding: '16px',
    borderRadius: '12px',
    fontWeight: '700',
    cursor: 'pointer',
    width: '100%',
    marginTop: '0',
    fontSize: '15px',
    boxShadow: '0 4px 12px rgba(5, 150, 105, 0.2)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  },
  labelSelector: {
    display: 'flex',
    gap: '12px',
    marginBottom: '24px',
  },
  labelOption: {
    padding: '10px 20px',
    borderRadius: '12px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    border: '1px solid #e2e8f0',
    backgroundColor: 'white',
    color: '#64748b',
    transition: 'all 0.2s ease',
  },
  labelOptionActive: {
    backgroundColor: '#059669',
    color: 'white',
    borderColor: '#059669',
    boxShadow: '0 4px 12px rgba(5, 150, 105, 0.2)',
  },
  checkboxContainer: {
    marginTop: '24px',
    marginBottom: '32px',
    padding: '16px',
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    color: '#334155',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    accentColor: '#059669',
    cursor: 'pointer',
  },
});
