// src/pages/user/UserReviews/styles.js

export const getStyles = (isMobile = false) => ({
  // Container
  container: {
    padding: isMobile ? '16px' : '0',
  },
  
  // Header
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    flexWrap: 'wrap',
    gap: '16px',
  },
  headerTitle: {
    fontSize: '22px',
    fontWeight: '700',
    color: '#0f172a',
    margin: 0,
  },
  headerSubtitle: {
    fontSize: '14px',
    color: '#64748b',
    margin: '4px 0 0 0',
  },
  
  // Tabs
  tabs: {
    display: 'flex',
    gap: '8px',
    backgroundColor: '#f1f5f9',
    padding: '6px',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  tab: {
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#64748b',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  tabActive: {
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#fff',
    backgroundColor: '#059669',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(5, 150, 105, 0.3)',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  tabBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    color: '#fff',
    padding: '2px 8px',
    borderRadius: '10px',
    fontSize: '12px',
    fontWeight: '700',
  },
  tabBadgeInactive: {
    backgroundColor: '#e2e8f0',
    color: '#64748b',
    padding: '2px 8px',
    borderRadius: '10px',
    fontSize: '12px',
    fontWeight: '700',
  },
  
  // Stats Row
  statsRow: {
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr 1fr' : 'repeat(4, 1fr)',
    gap: '12px',
    marginBottom: '24px',
  },
  statCard: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '16px',
    border: '1px solid #e2e8f0',
    textAlign: 'center',
  },
  statValue: {
    fontSize: '24px',
    fontWeight: '800',
    color: '#0f172a',
  },
  statLabel: {
    fontSize: '12px',
    color: '#64748b',
    marginTop: '4px',
  },
  
  // Pending Reviews Section
  pendingSection: {
    backgroundColor: '#fefce8',
    borderRadius: '16px',
    padding: '20px',
    marginBottom: '24px',
    border: '1px solid #fef08a',
  },
  pendingSectionTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#854d0e',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  pendingGrid: {
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr' : 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '16px',
  },
  pendingCard: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '16px',
    display: 'flex',
    gap: '12px',
    border: '1px solid #fef08a',
    transition: 'all 0.2s ease',
  },
  pendingProductImage: {
    width: '60px',
    height: '60px',
    borderRadius: '8px',
    objectFit: 'cover',
    backgroundColor: '#f1f5f9',
  },
  pendingProductInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  pendingProductName: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: '4px',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  pendingOrderInfo: {
    fontSize: '12px',
    color: '#64748b',
  },
  pendingReviewBtn: {
    padding: '8px 16px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#fff',
    backgroundColor: '#059669',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all 0.2s ease',
  },
  
  // My Reviews Section
  reviewsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  reviewCard: {
    backgroundColor: '#fff',
    borderRadius: '16px',
    padding: '20px',
    border: '1px solid #e2e8f0',
    transition: 'all 0.2s ease',
  },
  reviewCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '16px',
    gap: '16px',
    flexWrap: 'wrap',
  },
  reviewProductSection: {
    display: 'flex',
    gap: '12px',
    flex: 1,
  },
  reviewProductImage: {
    width: '70px',
    height: '70px',
    borderRadius: '10px',
    objectFit: 'cover',
    backgroundColor: '#f1f5f9',
  },
  reviewProductInfo: {
    flex: 1,
  },
  reviewProductName: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: '6px',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  reviewMeta: {
    fontSize: '12px',
    color: '#64748b',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  reviewStatusBadge: {
    padding: '4px 10px',
    borderRadius: '20px',
    fontSize: '11px',
    fontWeight: '600',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  reviewRating: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  reviewContent: {
    marginBottom: '16px',
  },
  reviewTitle: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: '8px',
  },
  reviewComment: {
    fontSize: '14px',
    color: '#475569',
    lineHeight: '1.6',
  },
  reviewMediaGrid: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    marginBottom: '16px',
  },
  reviewMediaItem: {
    width: '80px',
    height: '80px',
    borderRadius: '8px',
    overflow: 'hidden',
    cursor: 'pointer',
    border: '2px solid #e2e8f0',
    transition: 'all 0.2s ease',
  },
  reviewMediaImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  reviewMediaVideo: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    backgroundColor: '#000',
  },
  reviewFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: '12px',
    borderTop: '1px solid #f1f5f9',
  },
  reviewStats: {
    display: 'flex',
    gap: '16px',
    fontSize: '13px',
    color: '#64748b',
  },
  reviewStatItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  reviewActions: {
    display: 'flex',
    gap: '8px',
  },
  reviewActionBtn: {
    padding: '6px 12px',
    fontSize: '12px',
    fontWeight: '600',
    backgroundColor: '#f1f5f9',
    color: '#64748b',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    transition: 'all 0.2s ease',
  },
  reviewDeleteBtn: {
    padding: '6px 12px',
    fontSize: '12px',
    fontWeight: '600',
    backgroundColor: '#fef2f2',
    color: '#ef4444',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    transition: 'all 0.2s ease',
  },
  
  // Vendor Response
  vendorResponse: {
    backgroundColor: '#f0fdf4',
    borderRadius: '10px',
    padding: '14px',
    marginTop: '12px',
    border: '1px solid #bbf7d0',
  },
  vendorResponseHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
  },
  vendorResponseTitle: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#166534',
  },
  vendorResponseText: {
    fontSize: '13px',
    color: '#15803d',
    lineHeight: '1.5',
  },
  
  // Empty State
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
  },
  emptyIcon: {
    fontSize: '64px',
    color: '#cbd5e1',
    marginBottom: '16px',
  },
  emptyTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: '8px',
  },
  emptyText: {
    fontSize: '14px',
    color: '#64748b',
    marginBottom: '20px',
  },
  emptyBtn: {
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#fff',
    backgroundColor: '#059669',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  
  // Loading
  loadingContainer: {
    textAlign: 'center',
    padding: '60px 20px',
  },
  spinner: {
    width: '40px',
    height: '40px',
    border: '3px solid #e2e8f0',
    borderTopColor: '#059669',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    margin: '0 auto 16px',
  },
  
  // Review Modal
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    padding: '20px',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: '20px',
    width: '100%',
    maxWidth: '600px',
    maxHeight: '90vh',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 24px',
    borderBottom: '1px solid #e2e8f0',
    backgroundColor: '#f8fafc',
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#0f172a',
    margin: 0,
  },
  modalCloseBtn: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    backgroundColor: '#f1f5f9',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#64748b',
    fontSize: '18px',
    transition: 'all 0.2s ease',
  },
  modalBody: {
    padding: '24px',
    overflowY: 'auto',
    flex: 1,
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    padding: '20px 24px',
    borderTop: '1px solid #e2e8f0',
    backgroundColor: '#f8fafc',
  },
  
  // Form Elements
  formGroup: {
    marginBottom: '20px',
  },
  formLabel: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
    marginBottom: '8px',
  },
  formLabelRequired: {
    color: '#ef4444',
    marginLeft: '2px',
  },
  
  // Star Rating Input
  starRatingContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
  },
  starButton: {
    background: 'none',
    border: 'none',
    padding: '4px',
    cursor: 'pointer',
    transition: 'transform 0.15s ease',
  },
  starButtonHover: {
    transform: 'scale(1.2)',
  },
  ratingText: {
    marginLeft: '12px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#64748b',
  },
  ratingLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
    color: '#9ca3af',
    marginTop: '4px',
  },
  
  // Input Fields
  input: {
    width: '100%',
    padding: '12px 16px',
    fontSize: '14px',
    border: '1px solid #e2e8f0',
    borderRadius: '10px',
    outline: 'none',
    transition: 'all 0.2s ease',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    fontSize: '14px',
    border: '1px solid #e2e8f0',
    borderRadius: '10px',
    outline: 'none',
    transition: 'all 0.2s ease',
    boxSizing: 'border-box',
    resize: 'vertical',
    minHeight: '120px',
    fontFamily: 'inherit',
  },
  charCount: {
    textAlign: 'right',
    fontSize: '12px',
    color: '#9ca3af',
    marginTop: '4px',
  },
  
  // Media Upload
  mediaUploadSection: {
    marginBottom: '20px',
  },
  mediaUploadTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
    marginBottom: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  mediaUploadHint: {
    fontSize: '12px',
    color: '#9ca3af',
    marginBottom: '12px',
  },
  mediaUploadGrid: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  mediaUploadBox: {
    width: '100px',
    height: '100px',
    borderRadius: '12px',
    border: '2px dashed #d1d5db',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backgroundColor: '#fafafa',
  },
  mediaUploadBoxHover: {
    borderColor: '#059669',
    backgroundColor: '#f0fdf4',
  },
  mediaUploadIcon: {
    fontSize: '24px',
    color: '#9ca3af',
    marginBottom: '4px',
  },
  mediaUploadText: {
    fontSize: '11px',
    color: '#9ca3af',
  },
  mediaPreviewItem: {
    width: '100px',
    height: '100px',
    borderRadius: '12px',
    position: 'relative',
    overflow: 'hidden',
    border: '2px solid #e2e8f0',
  },
  mediaPreviewImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  mediaPreviewRemove: {
    position: 'absolute',
    top: '4px',
    right: '4px',
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
    color: '#fff',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '14px',
  },
  mediaPreviewVideo: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    backgroundColor: '#000',
  },
  videoPlayIcon: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    fontSize: '24px',
    color: '#fff',
    opacity: 0.9,
  },
  
  // Buttons
  primaryBtn: {
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#fff',
    backgroundColor: '#059669',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.2s ease',
  },
  secondaryBtn: {
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#64748b',
    backgroundColor: '#f1f5f9',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  disabledBtn: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  
  // Anonymous Option
  anonymousOption: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 16px',
    backgroundColor: '#f8fafc',
    borderRadius: '10px',
    marginTop: '16px',
    cursor: 'pointer',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    accentColor: '#059669',
    cursor: 'pointer',
  },
  anonymousLabel: {
    fontSize: '14px',
    color: '#374151',
  },
  anonymousHint: {
    fontSize: '12px',
    color: '#9ca3af',
    marginTop: '2px',
  },
  
  // Product Preview in Modal
  productPreview: {
    display: 'flex',
    gap: '12px',
    padding: '16px',
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    marginBottom: '20px',
  },
  productPreviewImage: {
    width: '60px',
    height: '60px',
    borderRadius: '8px',
    objectFit: 'cover',
  },
  productPreviewInfo: {
    flex: 1,
  },
  productPreviewName: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: '4px',
  },
  productPreviewMeta: {
    fontSize: '12px',
    color: '#64748b',
  },

  // Delete Confirmation
  deleteConfirmText: {
    fontSize: '14px',
    color: '#374151',
    textAlign: 'center',
    marginBottom: '20px',
    lineHeight: '1.6',
  },
  deleteConfirmBtns: {
    display: 'flex',
    justifyContent: 'center',
    gap: '12px',
  },
  deleteConfirmBtn: {
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#fff',
    backgroundColor: '#ef4444',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
  },
});
