// src/pages/user/UserProfile/styles.js

export const getStyles = (isMobile) => ({
  page: {
    backgroundColor: '#f8fafc',
    minHeight: '100vh',
    fontFamily: '"Inter", sans-serif',
  },
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: isMobile ? '20px 12px' : '40px 20px',
  },
  header: {
    marginBottom: isMobile ? '20px' : '32px',
  },
  title: {
    fontSize: isMobile ? '22px' : '28px',
    fontWeight: '800',
    color: '#1e293b',
    marginBottom: '8px',
  },
  subtitle: {
    color: '#64748b',
    fontSize: isMobile ? '13px' : '15px',
  },
  layout: {
    display: 'flex',
    gap: isMobile ? '16px' : '32px',
    flexDirection: isMobile ? 'column' : 'row',
  },
  sidebar: {
    width: isMobile ? '100%' : '280px',
    flexShrink: 0,
  },
  content: {
    flex: 1,
    backgroundColor: 'white',
    borderRadius: isMobile ? '16px' : '24px',
    padding: isMobile ? '20px' : '32px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
    minHeight: isMobile ? 'auto' : '600px',
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: isMobile ? '10px' : '12px',
    padding: isMobile ? '12px 16px' : '16px 20px',
    borderRadius: isMobile ? '12px' : '16px',
    cursor: 'pointer',
    marginBottom: isMobile ? '4px' : '8px',
    transition: 'all 0.2s',
    fontSize: isMobile ? '13px' : '15px',
    fontWeight: '600',
    color: '#64748b',
    backgroundColor: 'transparent',
    border: 'none',
    width: '100%',
    textAlign: 'left',
  },
  activeMenuItem: {
    backgroundColor: '#ecfdf5',
    color: '#059669',
  },
  sectionTitle: {
    fontSize: isMobile ? '18px' : '20px',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: isMobile ? '16px' : '24px',
    paddingBottom: isMobile ? '12px' : '16px',
    borderBottom: '1px solid #e2e8f0',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr',
    gap: isMobile ? '16px' : '24px',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: isMobile ? '6px' : '8px',
  },
  label: {
    fontSize: isMobile ? '12px' : '13px',
    fontWeight: '600',
    color: '#475569',
  },
  input: {
    padding: isMobile ? '10px 14px' : '12px 16px',
    borderRadius: isMobile ? '10px' : '12px',
    border: '1px solid #e2e8f0',
    fontSize: isMobile ? '13px' : '14px',
    color: '#1e293b',
    outline: 'none',
    transition: 'border-color 0.2s',
    backgroundColor: '#f8fafc',
    width: '100%',
    boxSizing: 'border-box',
  },
  button: {
    padding: isMobile ? '12px 24px' : '14px 32px',
    backgroundColor: '#059669',
    color: 'white',
    border: 'none',
    borderRadius: isMobile ? '10px' : '12px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'background 0.2s',
    marginTop: isMobile ? '16px' : '24px',
    width: isMobile ? '100%' : 'fit-content',
    justifyContent: 'center',
    fontSize: isMobile ? '14px' : '15px',
  },
  avatarSection: {
    display: 'flex',
    flexDirection: isMobile ? 'column' : 'row',
    alignItems: 'center',
    gap: isMobile ? '16px' : '24px',
    marginBottom: isMobile ? '24px' : '32px',
    padding: isMobile ? '16px' : '24px',
    backgroundColor: '#f8fafc',
    borderRadius: '20px',
  },
  avatarWrapper: {
    position: 'relative',
    width: '100px',
    height: '100px',
  },
  avatar: {
    width: '100%',
    height: '100%',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '4px solid white',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  uploadBtn: {
    position: 'absolute',
    bottom: '0',
    right: '0',
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: '#059669',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    border: '2px solid white',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  avatarInfo: {
    flex: 1,
    textAlign: isMobile ? 'center' : 'left',
  },
  avatarTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '4px',
  },
  avatarDesc: {
    fontSize: '13px',
    color: '#64748b',
    marginBottom: '12px',
  },
  deleteAvatarBtn: {
    padding: '8px 16px',
    backgroundColor: '#fee2e2',
    color: '#ef4444',
    border: 'none',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '60vh',
    gap: '16px',
    color: '#64748b',
  },
  spinner: {
    fontSize: '40px',
    color: '#059669',
    animation: 'spin 1s linear infinite',
  },
});
