// src/pages/user/Favorites/styles.js

export const getStyles = (isMobile) => ({
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: isMobile ? '20px 12px' : '40px 20px',
    fontFamily: '"Inter", sans-serif',
    minHeight: '60vh',
  },
  header: {
    display: 'flex',
    flexDirection: isMobile ? 'column' : 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    gap: '16px',
    backgroundColor: 'white',
    padding: isMobile ? '16px' : '12px 24px',
    borderRadius: '16px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  titleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: isMobile ? '100%' : 'auto',
    justifyContent: isMobile ? 'space-between' : 'flex-start',
  },
  title: {
    fontSize: isMobile ? '18px' : '20px',
    fontWeight: '700',
    color: '#0f172a',
    margin: 0,
  },
  countBadge: {
    backgroundColor: '#f1f5f9',
    color: '#64748b',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '600',
    border: '1px solid #e2e8f0',
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'nowrap',
    width: isMobile ? '100%' : 'auto',
    overflowX: isMobile ? 'auto' : 'visible',
    paddingBottom: isMobile ? '4px' : '0',
  },
  actionBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '0 16px',
    borderRadius: '8px',
    border: '1px solid #e2e8f0',
    backgroundColor: 'white',
    color: '#475569',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    whiteSpace: 'nowrap',
    height: '40px',
    fontFamily: 'inherit',
  },
  primaryBtn: {
    backgroundColor: '#059669',
    color: 'white',
    border: '1px solid #059669',
    boxShadow: 'none',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: isMobile ? 'repeat(2, 1fr)' : 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: isMobile ? '12px' : '24px',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: isMobile ? '16px' : '20px',
    border: '1px solid #f1f5f9',
    overflow: 'hidden',
    position: 'relative',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
    display: 'flex',
    flexDirection: 'column',
  },
  cardHover: {
    transform: 'translateY(-5px)',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: isMobile ? '180px' : '280px',
    backgroundColor: '#f8fafc',
    overflow: 'hidden',
    display: 'block',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    transition: 'transform 0.5s ease',
    padding: isMobile ? '8px' : '16px',
  },
  discountBadge: {
    position: 'absolute',
    top: isMobile ? '8px' : '16px',
    left: isMobile ? '8px' : '16px',
    backgroundColor: '#ef4444',
    color: 'white',
    fontSize: isMobile ? '10px' : '12px',
    fontWeight: '700',
    padding: isMobile ? '2px 6px' : '4px 8px',
    borderRadius: '6px',
    zIndex: 2,
  },
  removeBtn: {
    position: 'absolute',
    top: isMobile ? '8px' : '16px',
    right: isMobile ? '8px' : '16px',
    width: isMobile ? '30px' : '36px',
    height: isMobile ? '30px' : '36px',
    borderRadius: '50%',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    backdropFilter: 'blur(4px)',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ef4444',
    cursor: 'pointer',
    zIndex: 2,
    transition: 'all 0.2s',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  content: {
    padding: isMobile ? '12px' : '20px',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  vendorName: {
    fontSize: isMobile ? '10px' : '12px',
    color: '#94a3b8',
    fontWeight: '600',
    marginBottom: isMobile ? '4px' : '8px',
  },
  productTitle: {
    fontSize: isMobile ? '13px' : '16px',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: isMobile ? '8px' : '12px',
    lineHeight: '1.4',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    height: isMobile ? '36px' : '44px',
    textDecoration: 'none',
  },
  priceRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    marginBottom: '16px',
    marginTop: 'auto',
  },
  price: {
    fontSize: isMobile ? '16px' : '20px',
    fontWeight: '800',
    color: '#059669',
  },
  oldPrice: {
    fontSize: isMobile ? '12px' : '14px',
    color: '#94a3b8',
    textDecoration: 'line-through',
  },
  stockStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: '600',
    marginBottom: '20px',
  },
  addToCartBtn: {
    width: '100%',
    padding: '12px',
    backgroundColor: '#0f172a',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'all 0.2s',
  },
  emptyState: {
    textAlign: 'center',
    padding: '80px 20px',
    backgroundColor: '#f8fafc',
    borderRadius: '32px',
    border: '2px dashed #e2e8f0',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyIcon: {
    fontSize: '64px',
    color: '#cbd5e1',
    marginBottom: '24px',
  },
  emptyTitle: {
    fontSize: '24px',
    fontWeight: '800',
    color: '#1e293b',
    marginBottom: '12px',
  },
  emptyText: {
    color: '#64748b',
    marginBottom: '32px',
    maxWidth: '400px',
    lineHeight: '1.6',
  },
  startShoppingBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '16px 32px',
    backgroundColor: '#059669',
    color: 'white',
    textDecoration: 'none',
    borderRadius: '16px',
    fontWeight: '700',
    transition: 'all 0.2s',
    boxShadow: '0 10px 20px -5px rgba(5, 150, 105, 0.3)',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '60vh',
    gap: '16px',
    color: '#64748b',
  },
  spinner: {
    fontSize: '40px',
    color: '#059669',
    animation: 'spin 1s linear infinite',
  },
});
