// src/pages/admin/Reviews/styles.js

export const getStyles = (isMobile = false) => ({
  container: {
    padding: isMobile ? '16px' : '32px',
    backgroundColor: '#F3F4F6',
    minHeight: '100vh',
  },
  
  // Header
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: isMobile ? 'flex-start' : 'center',
    marginBottom: isMobile ? '16px' : '24px',
    background: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)',
    padding: isMobile ? '20px 16px' : '28px 32px',
    borderRadius: '16px',
    border: '1px solid #e2e8f0',
    flexDirection: isMobile ? 'column' : 'row',
    gap: isMobile ? '16px' : '0'
  },
  titleGroup: {},
  title: {
    fontSize: isMobile ? '20px' : '26px',
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: '-0.02em',
    margin: 0,
  },
  subtitle: {
    fontSize: isMobile ? '13px' : '15px',
    color: '#64748b',
    margin: '6px 0 0 0',
  },
  headerActions: {
    display: 'flex',
    gap: '12px',
    width: isMobile ? '100%' : 'auto'
  },
  exportBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    backgroundColor: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: '10px',
    color: '#111827',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
    flex: isMobile ? 1 : 'none',
    justifyContent: isMobile ? 'center' : 'flex-start',
    minHeight: isMobile ? '44px' : 'auto'
  },

  // Tabs
  tabsContainer: {
    display: 'flex',
    gap: '8px',
    marginBottom: '24px',
    backgroundColor: '#fff',
    padding: '8px',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    width: 'fit-content',
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 24px',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '8px',
    color: '#64748b',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  tabActive: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 24px',
    backgroundColor: '#059669',
    border: 'none',
    borderRadius: '8px',
    color: '#fff',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    boxShadow: '0 4px 6px rgba(5, 150, 105, 0.3)',
  },

  // Stats
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: isMobile ? 'repeat(2, 1fr)' : 'repeat(4, 1fr)',
    gap: isMobile ? '12px' : '16px',
    marginBottom: isMobile ? '16px' : '24px',
  },
  statCard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: '20px 24px',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    transition: 'all 0.2s',
  },
  statInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  statLabel: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#64748b',
  },
  statValue: {
    fontSize: '28px',
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: '-0.02em',
  },
  statIconBox: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Toolbar
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: '16px 20px',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    marginBottom: '20px',
    flexWrap: 'wrap',
    gap: '16px',
  },
  toolbarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  searchWrapper: {
    position: 'relative',
    width: '320px',
  },
  searchIcon: {
    position: 'absolute',
    left: '14px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#9ca3af',
    fontSize: '14px',
  },
  searchInput: {
    width: '100%',
    padding: '10px 14px 10px 42px',
    border: '1px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '14px',
    color: '#111827',
    outline: 'none',
    backgroundColor: '#f9fafb',
  },
  filterSelect: {
    padding: '10px 16px',
    border: '1px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '500',
    color: '#111827',
    backgroundColor: '#f9fafb',
    cursor: 'pointer',
    outline: 'none',
    minWidth: '150px',
  },
  bulkActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  selectedCount: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#6b7280',
    padding: '8px 16px',
    backgroundColor: '#f3f4f6',
    borderRadius: '8px',
  },
  bulkApproveBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    backgroundColor: '#10b981',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  bulkRejectBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    backgroundColor: '#ef4444',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },

  // Table
  tableContainer: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    padding: '14px 16px',
    textAlign: 'left',
    fontSize: '12px',
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    backgroundColor: '#f8fafc',
    borderBottom: '1px solid #e5e7eb',
  },
  tr: {
    transition: 'background-color 0.2s',
  },
  td: {
    padding: '14px 16px',
    borderBottom: '1px solid #f1f5f9',
    fontSize: '14px',
    color: '#374151',
    verticalAlign: 'middle',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
    accentColor: '#059669',
  },
  loadingCell: {
    textAlign: 'center',
    padding: '60px 20px',
    color: '#6b7280',
    fontSize: '15px',
  },
  emptyCell: {
    textAlign: 'center',
    padding: '80px 20px',
    color: '#6b7280',
    fontSize: '15px',
  },
  loader: {
    width: '32px',
    height: '32px',
    border: '3px solid #e5e7eb',
    borderTopColor: '#059669',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    margin: '0 auto 16px',
  },

  // User Cell
  userCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  userAvatar: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    backgroundColor: '#e0e7ff',
    color: '#4f46e5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userName: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#111827',
  },
  userEmail: {
    fontSize: '12px',
    color: '#6b7280',
  },

  // Product Cell
  productCell: {
    display: 'flex',
    alignItems: 'center',
  },
  productName: {
    fontSize: '13px',
    color: '#374151',
    fontWeight: '500',
  },

  // Vendor Cell
  vendorCell: {
    display: 'flex',
    alignItems: 'center',
  },

  // Rating
  starsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
  },
  ratingText: {
    marginLeft: '8px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#374151',
  },

  // Comment Cell
  commentCell: {
    maxWidth: '250px',
  },
  commentTitle: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#111827',
    marginBottom: '4px',
  },
  commentText: {
    fontSize: '12px',
    color: '#6b7280',
    lineHeight: '1.4',
  },
  mediaIndicator: {
    fontSize: '11px',
    color: '#059669',
    marginTop: '4px',
    fontWeight: '500',
  },

  // Status Badge
  statusBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: '600',
  },
  rejectionReason: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    color: '#ef4444',
    marginTop: '6px',
  },

  // Date Cell
  dateCell: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#374151',
  },
  timeCell: {
    fontSize: '11px',
    color: '#9ca3af',
    marginTop: '2px',
  },

  // Action Buttons
  actionButtons: {
    display: 'flex',
    gap: '8px',
  },
  viewBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    backgroundColor: '#e0e7ff',
    color: '#4f46e5',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  approveBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    backgroundColor: '#d1fae5',
    color: '#059669',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  rejectBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    backgroundColor: '#fee2e2',
    color: '#ef4444',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },

  // Modal Overlay
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: '20px',
    width: '100%',
    maxWidth: '700px',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 25px 50px rgba(0, 0, 0, 0.25)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '24px 28px',
    borderBottom: '1px solid #e5e7eb',
    backgroundColor: '#f8fafc',
  },
  modalTitle: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#0f172a',
    margin: 0,
  },
  modalCloseBtn: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    backgroundColor: '#f1f5f9',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#64748b',
    fontSize: '18px',
    transition: 'all 0.2s',
  },
  modalBody: {
    padding: '28px',
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    padding: '20px 28px',
    borderTop: '1px solid #e5e7eb',
    backgroundColor: '#f8fafc',
  },
  modalCancelBtn: {
    padding: '12px 24px',
    backgroundColor: '#f1f5f9',
    color: '#64748b',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  modalSubmitBtn: {
    padding: '12px 24px',
    backgroundColor: '#ef4444',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  modalApproveBtn: {
    padding: '12px 24px',
    backgroundColor: '#10b981',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  modalRejectBtn: {
    padding: '12px 24px',
    backgroundColor: '#ef4444',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },

  // Detail Modal Sections
  detailSection: {
    marginBottom: '24px',
    padding: '20px',
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
  },
  detailSectionTitle: {
    fontSize: '14px',
    fontWeight: '700',
    color: '#374151',
    marginBottom: '16px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  detailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '12px',
  },
  detailLabel: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#6b7280',
  },
  detailValue: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#111827',
    textAlign: 'right',
    maxWidth: '60%',
  },
  reviewContent: {
    backgroundColor: '#fff',
    padding: '20px',
    borderRadius: '10px',
    border: '1px solid #e5e7eb',
  },
  reviewTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#111827',
    marginBottom: '12px',
  },
  reviewComment: {
    fontSize: '14px',
    color: '#374151',
    lineHeight: '1.7',
  },
  mediaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '12px',
    marginTop: '16px',
  },
  mediaItem: {
    aspectRatio: '1',
    borderRadius: '8px',
    overflow: 'hidden',
    border: '1px solid #e5e7eb',
  },
  mediaImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },

  // Textarea
  textarea: {
    width: '100%',
    padding: '14px',
    border: '1px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '14px',
    color: '#111827',
    resize: 'vertical',
    minHeight: '120px',
    outline: 'none',
    fontFamily: 'inherit',
  },

  // Banned Words Tab
  bannedWordsContainer: {
    backgroundColor: '#fff',
    borderRadius: '16px',
    border: '1px solid #e5e7eb',
    overflow: 'hidden',
  },
  bannedWordsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 24px',
    borderBottom: '1px solid #e5e7eb',
    backgroundColor: '#f8fafc',
  },
  addWordBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    backgroundColor: '#059669',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  wordsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '12px',
    padding: '24px',
  },
  wordCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 18px',
    backgroundColor: '#fef2f2',
    borderRadius: '10px',
    border: '1px solid #fecaca',
  },
  wordText: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#991b1b',
  },
  wordDeleteBtn: {
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    backgroundColor: '#ef4444',
    color: '#fff',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '12px',
  },
  emptyWords: {
    textAlign: 'center',
    padding: '60px 20px',
    color: '#6b7280',
  },
  addWordForm: {
    display: 'flex',
    gap: '12px',
    padding: '20px 24px',
    borderTop: '1px solid #e5e7eb',
    backgroundColor: '#f8fafc',
  },
  addWordInput: {
    flex: 1,
    padding: '12px 16px',
    border: '1px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '14px',
    outline: 'none',
  },
  addWordSubmitBtn: {
    padding: '12px 24px',
    backgroundColor: '#059669',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },

  // Banned Words Tab - Additional Styles
  bannedWordsStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '16px',
    marginBottom: '24px',
  },
  bannedWordStatCard: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    padding: '20px 24px',
    textAlign: 'center',
  },
  bannedWordStatValue: {
    fontSize: '32px',
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: '4px',
  },
  bannedWordStatLabel: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#64748b',
  },
  bannedWordsAddSection: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    marginBottom: '20px',
    overflow: 'hidden',
  },
  bannedWordsSectionTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#0f172a',
    margin: 0,
    padding: '20px 24px',
    borderBottom: '1px solid #e5e7eb',
    backgroundColor: '#f8fafc',
    display: 'flex',
    alignItems: 'center',
  },
  regexToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '13px',
    fontWeight: '500',
    color: '#6b7280',
    cursor: 'pointer',
    padding: '10px 16px',
    backgroundColor: '#f3f4f6',
    borderRadius: '8px',
    whiteSpace: 'nowrap',
  },
  bulkAddBtn: {
    padding: '10px 20px',
    backgroundColor: '#f3f4f6',
    color: '#374151',
    border: '1px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  bulkAddSection: {
    padding: '20px 24px',
    backgroundColor: '#f9fafb',
    borderTop: '1px solid #e5e7eb',
  },
  bulkAddTextarea: {
    width: '100%',
    padding: '12px 16px',
    border: '1px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '14px',
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  cancelBulkBtn: {
    padding: '10px 20px',
    backgroundColor: '#fff',
    color: '#374151',
    border: '1px solid #e5e7eb',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  bannedWordsToolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: '16px 20px',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    marginBottom: '20px',
  },
  searchBox: {
    position: 'relative',
    width: '300px',
  },
  bulkDeleteBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    backgroundColor: '#ef4444',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  bannedWordsGrid: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    overflow: 'hidden',
    minHeight: '300px',
  },
  loadingState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    color: '#6b7280',
  },
  spinner: {
    width: '40px',
    height: '40px',
    border: '3px solid #e5e7eb',
    borderTop: '3px solid #059669',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    marginBottom: '16px',
  },
  errorState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    color: '#ef4444',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    color: '#6b7280',
  },
  selectAllRow: {
    padding: '16px 24px',
    borderBottom: '1px solid #e5e7eb',
    backgroundColor: '#f8fafc',
  },
  selectAllLabel: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '14px',
    fontWeight: '500',
    color: '#374151',
    cursor: 'pointer',
  },
  wordsContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))',
    gap: '12px',
    padding: '24px',
  },
  wordCheckbox: {
    marginRight: '12px',
    width: '16px',
    height: '16px',
    cursor: 'pointer',
  },
  wordContent: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    overflow: 'hidden',
  },
  regexBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '2px 8px',
    backgroundColor: '#8b5cf6',
    color: '#fff',
    fontSize: '10px',
    fontWeight: '600',
    borderRadius: '4px',
    whiteSpace: 'nowrap',
  },
  deleteConfirm: {
    display: 'flex',
    gap: '4px',
  },
  confirmYes: {
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    backgroundColor: '#10b981',
    color: '#fff',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '12px',
  },
  confirmNo: {
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    backgroundColor: '#6b7280',
    color: '#fff',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '12px',
  },
});
